import io
import json
import logging
from typing import Dict, Any, Optional, List
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from pptx import Presentation
from pptx.util import Inches, Pt

from logging_config import get_logger

logger = get_logger(__name__)

class ExportManager:
    """
    Manages the export of analysis results to different formats (PDF, PPTX).
    """

    def __init__(self):
        # Initialize styles for PDF
        self.styles = getSampleStyleSheet()
        if 'Code' not in self.styles:
            self.styles.add(ParagraphStyle(name='Code', fontSize=8, fontName='Courier'))

    def _render_chart(self, viz_data: Dict[str, Any]) -> Optional[io.BytesIO]:
        """
        Render a chart from visualization data using matplotlib.
        Returns a BytesIO stream containing the image.
        """
        if not viz_data or 'data' not in viz_data:
            return None

        try:
            chart_type = viz_data.get('type')
            data = viz_data.get('data', {})
            labels = data.get('labels', [])
            values = data.get('values', [])
            
            # Create a new figure
            plt.figure(figsize=(8, 5))
            
            if chart_type == 'bar':
                plt.bar(labels, values)
            elif chart_type == 'line':
                plt.plot(labels, values, marker='o')
            elif chart_type == 'scatter':
                plt.scatter(labels, values)
            elif chart_type == 'pie':
                plt.pie(values, labels=labels, autopct='%1.1f%%')
            elif chart_type == 'area':
                plt.stackplot(labels, values)
            else:
                logger.warning(f"Unsupported chart type for rendering: {chart_type}")
                return None

            plt.title(viz_data.get('title', 'Analysis Chart'))
            plt.tight_layout()
            
            # Save to buffer
            buf = io.BytesIO()
            plt.savefig(buf, format='png', dpi=100)
            plt.close()
            buf.seek(0)
            return buf
            
        except Exception as e:
            logger.error(f"Error rendering chart: {e}", exc_info=True)
            return None

    def generate_pdf(self, query: str, response: str, viz_data: Optional[Dict[str, Any]] = None) -> io.BytesIO:
        """
        Generate a PDF report.
        """
        logger.info("Generating PDF report")
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []

        # Title
        story.append(Paragraph("Analysis Report", self.styles['Title']))
        story.append(Spacer(1, 12))

        # Query Section
        story.append(Paragraph("Query", self.styles['Heading2']))
        story.append(Paragraph(query, self.styles['Normal']))
        story.append(Spacer(1, 12))

        # Response Section
        story.append(Paragraph("Analysis", self.styles['Heading2']))
        # Split response by newlines for better formatting
        for line in response.split('\n'):
            if line.strip():
                story.append(Paragraph(line, self.styles['Normal']))
                story.append(Spacer(1, 6))
        story.append(Spacer(1, 12))

        # Visualization Section
        if viz_data:
            chart_img_buf = self._render_chart(viz_data)
            if chart_img_buf:
                story.append(Paragraph("Visualization", self.styles['Heading2']))
                # Create ReportLab Image
                img = RLImage(chart_img_buf, width=6*inch, height=4*inch)
                story.append(img)
                
                # Chart description/title
                if viz_data.get('title'):
                    story.append(Paragraph(f"Figure: {viz_data.get('title')}", self.styles['Italic']))

        try:
            doc.build(story)
        except Exception as e:
            logger.error(f"Error building PDF: {e}", exc_info=True)
            raise

        buffer.seek(0)
        return buffer

    def generate_pptx(self, query: str, response: str, viz_data: Optional[Dict[str, Any]] = None) -> io.BytesIO:
        """
        Generate a PowerPoint presentation.
        """
        logger.info("Generating PPTX report")
        prs = Presentation()

        # Slide 1: Title
        slide_layout = prs.slide_layouts[0] # Title Slide
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = "Analysis Report"
        subtitle.text = f"Generated by Vantage AI\n{query[:50]}..." if len(query) > 50 else f"Generated by Vantage AI\n{query}"

        # Slide 2: Analysis Text
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        title.text = "Analysis Results"
        
        # Add text box for response
        body_shape = slide.shapes.placeholders[1]
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        # Add paragraphs (truncate if too long for one slide - simple version)
        tf.text = response[:1000] 
        if len(response) > 1000:
            p = tf.add_paragraph()
            p.text = "...(text truncated)..."

        # Slide 3: Visualization (if exists)
        if viz_data:
            chart_img_buf = self._render_chart(viz_data)
            if chart_img_buf:
                slide_layout = prs.slide_layouts[5] # Title Only
                slide = prs.slides.add_slide(slide_layout)
                title = slide.shapes.title
                title.text = viz_data.get('title', 'Visualization')
                
                # Add image
                left = Inches(1)
                top = Inches(1.5)
                height = Inches(5)
                slide.shapes.add_picture(chart_img_buf, left, top, height=height)

        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer