"""initial_schema

Revision ID: 23dabd3875a7
Revises: 
Create Date: 2026-01-25 07:01:33.818208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23dabd3875a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('db_connection_string', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_api_key'), 'organizations', ['api_key'], unique=True)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('shared_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('visualization', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_reports_expires_at'), 'shared_reports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shared_reports_org_id'), 'shared_reports', ['org_id'], unique=False)
    op.drop_table('staff')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('orders_data')
    op.drop_table('products_data')
    op.drop_table('payments_data')
    op.drop_table('h__sport_employees')
    op.drop_table('h__sport_orders')
    op.drop_table('h__sport_customers')
    op.drop_table('sample_data_excel')
    op.drop_table('h__sport_employees_copy_1769312835')
    op.drop_table('sample_data_csv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_data_csv',
    sa.Column('lisa_west', sa.TEXT(), nullable=True),
    sa.Column('andrew23_example_com', sa.TEXT(), nullable=True),
    sa.Column('col_465_852_8470', sa.TEXT(), nullable=True),
    sa.Column('unit_5183_box_8914_dpo_ap_26775', sa.TEXT(), nullable=True),
    sa.Column('perezfort', sa.TEXT(), nullable=True),
    sa.Column('honduras', sa.TEXT(), nullable=True),
    sa.Column('col_2001_08_05', sa.TEXT(), nullable=True),
    sa.Column('col_83302', sa.FLOAT(), nullable=True)
    )
    op.create_table('h__sport_employees_copy_1769312835',
    sa.Column('unnamed_1', sa.TEXT(), nullable=True),
    sa.Column('unnamed_3', sa.TEXT(), nullable=True)
    )
    op.create_table('sample_data_excel',
    sa.Column('sample_data', sa.TEXT(), nullable=True),
    sa.Column('unnamed_1', sa.TEXT(), nullable=True),
    sa.Column('unnamed_2', sa.TEXT(), nullable=True),
    sa.Column('unnamed_3', sa.TEXT(), nullable=True),
    sa.Column('unnamed_4', sa.TEXT(), nullable=True),
    sa.Column('unnamed_5', sa.TEXT(), nullable=True),
    sa.Column('unnamed_6', sa.TEXT(), nullable=True),
    sa.Column('unnamed_7', sa.TEXT(), nullable=True)
    )
    op.create_table('h__sport_customers',
    sa.Column('customerid', sa.BIGINT(), nullable=True),
    sa.Column('firstname', sa.TEXT(), nullable=True),
    sa.Column('lastname', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('zipcode', sa.BIGINT(), nullable=True)
    )
    op.create_table('h__sport_orders',
    sa.Column('orderid', sa.BIGINT(), nullable=True),
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('totaldue', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('customerid', sa.BIGINT(), nullable=True),
    sa.Column('salespersonid', sa.BIGINT(), nullable=True),
    sa.Column('customerscomment', sa.FLOAT(), nullable=True),
    sa.Column('salespersonscomment', sa.FLOAT(), nullable=True)
    )
    op.create_table('h__sport_employees',
    sa.Column('unnamed_0', sa.FLOAT(), nullable=True),
    sa.Column('unnamed_1', sa.TEXT(), nullable=True),
    sa.Column('unnamed_2', sa.TEXT(), nullable=True),
    sa.Column('unnamed_3', sa.TEXT(), nullable=True)
    )
    op.create_table('payments_data',
    sa.Column('orderid', sa.BIGINT(), nullable=True),
    sa.Column('paymentmethod', sa.TEXT(), nullable=True),
    sa.Column('paymentdate', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True)
    )
    op.create_table('products_data',
    sa.Column('productname', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.TEXT(), nullable=True),
    sa.Column('stockquantity', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True)
    )
    op.create_table('orders_data',
    sa.Column('userid', sa.BIGINT(), nullable=True),
    sa.Column('orderdate', sa.TEXT(), nullable=True),
    sa.Column('totalamount', sa.FLOAT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True)
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('staff_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('product', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True)
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.drop_index(op.f('ix_shared_reports_org_id'), table_name='shared_reports')
    op.drop_index(op.f('ix_shared_reports_expires_at'), table_name='shared_reports')
    op.drop_table('shared_reports')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_api_key'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
